### PR TITLE
Check for steady state in is_deployed

### PR DESCRIPTION
**Pull request by Equlnox**
https://rippling.atlassian.net/browse/INFRA-768

### CODE REVIEW

**Comment by Equlnox** [comment]
On selecting the wrong port, the deployment doesn't complete
[
Screenshot 2020-09-17 at 4 24 00 PM
](url)

When the correct port is selected deployment completes
Screenshot 2020-09-17 at 4 36 16 PM

**Comment by aswinkarthik** [comment]
Can you increase CLI version?

**Comment by Equlnox** [comment]
> Can you increase CLI version?

Increased

**Comment by aswinkarthik** [comment]
Some additional context:

This logic is based on the AWS CLI version of waiting for services to be stable: https://docs.aws.amazon.com/cli/latest/reference/ecs/wait/services-stable.html

The `STEADY_STATE` status is only applicable for `TaskSets` which we do not use. And hence it is not returned as part of our `describe_services` API. 

@sannithibalaji @siliconsenthil

**Pull request merged**
