### PR TITLE
Build and upload docker image to ECR

### PR DESCRIPTION
**Pull request by alanseong**
Fixed `upload_to_ecr` to use a proper `aws region` from `environment` and refactored code

### CODE REVIEW

**Comment by siliconsenthil** [comment]
Hey, this is already done in https://github.com/GetSimpl/cloudlift/pull/18

**Comment by alanseong** [comment]
> Hey, this is already done in [GetSimpl#18](https://github.com/GetSimpl/cloudlift/pull/18)

darn, ours felt behind already :)

**Comment by alanseong** [comment]
i will wait till that https://github.com/GetSimpl/cloudlift/pull/18  gets merged then will merge `upload_to_ecr` refactoring

**Comment by siliconsenthil** [comment]
Yeah. Rather you can use the branch in our repo. https://github.com/Rippling/cloudlift/tree/config-flexibility?files=1


Maybe we can merge this branch to our master

**Comment by siliconsenthil** [comment]
Closing as these features are done as part of config-flexibility PR

**Pull request closed without merging**
